apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: chatbot-oct10-pr2
  janus-idp.io/tekton: chatbot-oct10-pr2
  backstage.io/kubernetes-id: chatbot-oct10-pr2
  backstage.io/kubernetes-namespace: chatbot-oct10-pr2 
  app.kubernetes.io/part-of: chatbot-oct10-pr2
resources: 
- initialize-namespace.yaml
- deployment-model-server.yaml
- service-model-server.yaml
- deployment.yaml
- route.yaml
- service.yaml
- model-config.yaml
- rhoai/
